config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  constraints(SubdomainPresent) do
    root 'tasks#index', as: :subdomain_root
    devise_for :users
    resources :users, only: [:index, :update, :edit, :destroy]
    resources :tasks do
      collection do
        get 'search'
        get 'due_now'
      end
    end
    
    get 'tasks/filters/status/:status_id' => 'tasks#index'
    get 'tasks/filters/priority/:priority_id' => 'tasks#index'
    get 'tasks/filters/product/:product_id' => 'tasks#index'
    get 'tasks/filters/all/:all_tasks' => 'tasks#index'
    
    resources :tasks do
      resources :task_details
    end
    
    resources :clients do
      resources :client_contacts
      collection do
        post :sort
        get 'contacts'
      end
    end

    resources :statuses do
      collection { post :sort }
    end
    
    resources :priorities do
      collection { post :sort }
    end

    resources :products do
      collection { post :sort }
    end
    
    resources :projects do
      resources :tasks
    end

    resources :searches

    resources :todo_lists do
      resources :todo_items do
        member do
          patch :complete
        end
      end
    end
    
    get 'analytics/show'
    
    get 'pages/index'
    resources :billings, only: [:new, :show, :create]
    get 'tags/:tag', to: 'tasks#index', as: :tag
    get 'welcome/documentation' => 'welcome#documentation'
  end

  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
    get 'pages/test' => 'pages#test'
    get 'welcome/index' => 'welcome#index'
    get 'welcome/test' => 'welcome#test'
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessor :client_name
  attr_accessor :status_name
  attr_accessor :priority_name
  attr_accessor :product_name
  acts_as_taggable
  searchkick index_name: -> { [Apartment::Tenant.current, model_name.plural, Rails.env].join('_') }
  belongs_to :status
  belongs_to :product
  belongs_to :priority
  belongs_to :client
  belongs_to :project
  has_many :task_details, dependent: :destroy
  validates :status, :product, :priority, :title, :client, :assigned_to, presence: true
  VALID_EMAIL_REGEX = /\A(([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+([,.](([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5}){1,25})+)*\z/i
  validates :notify_email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, allow_blank: true
  scope :alltasks, -> {}
 
  delegate :name, :to => :status, :prefix => true
  delegate :name, :to => :priority, :prefix => true
  delegate :name, :to => :product, :prefix => true
  delegate :name, :to => :client, :prefix => true

  def status_color_name
    self.status.color_name
  end

  def product_color_name
    self.product.color_name
  end

  def priority_color_name
    self.priority.color_name
  end

  def client_color_name
    self.client.color_name
  end
 
  def self.searchkick_index
    index_name = [Apartment::Tenant.current, model_name.plural, Rails.env].join('_')
    Searchkick::Index.new(index_name)
  end

  def time_spent_by(user_id)
    time_spent = 0
    task_details.each do |td|
      if td.user_id == user_id
        time_spent += td.time_spent
      end
    end
    time_spent
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource

  def index
    @statuses = Status.includes(:color).order('position')
    @priorities = Priority.includes(:color).order('position')
    @products = Product.includes(:color).order('position')
    @tasks = Task.includes(:status, :client, :priority => :color, :product => :color)
    if params[:status_id]
      @tasks = @tasks.where("status_id = ?", params[:status_id])
    elsif params[:priority_id]
      @tasks = @tasks.where("priority_id = ?", params[:priority_id])
    elsif params[:product_id]
      @tasks = @tasks.where("product_id = ?", params[:product_id])
    elsif params[:tag]
      @tasks = @tasks.tagged_with(params[:tag])
    elsif params[:all_tasks]
      @tasks = @tasks
    else
      @tasks = @tasks.where('assigned_to = ?', current_user).order('created_at DESC').
          reject { |t| t.status.default_view != true }
    end
      respond_to :html, :json
  end

  def show
    @task_details = @task.task_details.order("created_at")
      respond_to :html, :json
  end

  def new
    if Task.all.count <= 1
      #To put back when elastic search issue gets sorted out...
      #Task.reindex
      #TaskDetail.reindex
    end
  end

  def create
    tp = task_params

    @task.client_id = check_for_new_client(tp) if !tp[:client_name].blank?
    @task.status_id = check_for_new_status(tp) if !tp[:status_name].blank?
    @task.priority_id = check_for_new_priority(tp) if !tp[:priority_name].blank?
    @task.product_id = check_for_new_product(tp) if !tp[:product_name].blank?

    @task.created_by = current_user.id

    if @task.save
      redirect_to new_task_task_detail_path(@task), flash: { success: "Task created successfully!" }
    else
      render :new
    end
  end

  def edit
  end

  def update
    @task.update(task_params)
    if @task.save
      UserNotifier.send_status_update(@task, current_account).deliver_now
      redirect_to @task, flash: { success: "Task successfully updated" }
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.js
    end
  end

  def search
    begin
      if params[:search].present?
        perform_search
      else
        @tasks = Task.includes(:status, :client, :priority => :color, :product => :color, :status => :color)
        @task_details = TaskDetail.includes(:task)
      end
    rescue Exception
      Task.reindex
      TaskDetail.reindex
      perform_search
    end
  end

  def due_now
    @tasks = Task.includes(:status, :client, :priority => :color, :product => :color).where('due_date <= ? AND assigned_to = ?', Time.now, current_user).order("due_date").
    reject { |t| t.status.is_complete == true }
  end

  private
    def task_params
      params.require(:task).permit(:title, :status_id,
        :product_id, :priority_id, :client_id, :alternate_id, :tag_list, :project_id,
        :assigned_to, :billable, :client_name, :status_name, :priority_name, :product_name, :notify_email, :due_date)
    end

    def check_for_new_client(tp)
      c = Client.create(name: tp[:client_name])
      c.id
    end
    
    def check_for_new_status(tp)
      color = Color.find_by(name: "Grey")
      s = Status.create(name: tp[:status_name], color_id: color.id, default_view: true)
      s.id
    end

    def check_for_new_priority(tp)
      color = Color.find_by(name: "Grey")
      p = Priority.create(name: tp[:priority_name], color_id: color.id)
      p.id      
    end

    def check_for_new_product(tp)
      color = Color.find_by(name: "Grey")
      p = Product.create(name: tp[:product_name], color_id: color.id)
      p.id
    end

    def perform_search
      @tasks = Task.includes(:status, :client, :priority => :color, :product => :color, :status => :color).search params[:search], fields: [:title, :alternate_id, :id]
      @task_details = TaskDetail.includes(:task).search params[:search], fields: [:body]      
    end
end

app/helpers/tasks_helper.rb
# - View helpers for labels
module TasksHelper
  def label_lookup(name)
    case name
    when 'Green'
      'success'
    when 'Red'
      'danger'
    when 'Blue'
      'primary'
    when 'Grey'
      'default'
    when 'Light Blue'
      'info'
    when 'Orange'
      'warning'
    end
  end

  def show_status(task)
    if task.status
      task.status_name
    else
      'N/A'
    end
  end

  def show_product(task)
    if task.product
      task.product_name
    else
      'N/A'
    end
  end

  def show_priority(task)
    if task.priority
      task.priority_name
    else
      'N/A'
    end
  end

  def show_client(task)
    if task.client
      task.client_name
    else
      'N/A'
    end
  end

  def show_summary(task)
    if task.summary
      content_tag(:p, task.summary.html_safe)
    else
      'N/A'
    end
  end

  def label_id(task)
    content_tag(:span, class: 'label label-default') do
      task.id.to_s
    end
  end

  def label_client(task)
    if task.client
      content_tag(:span, class: 'label label-default') do
        link_to(show_client(task), edit_task_path(task), style: 'color: white')
      end
    else
      show_client(task)
    end
  end

  def label_date(task)
    content_tag(:span, class: 'label label-default') do
      link_to(
        task.created_at.getlocal,
        edit_task_path(task),
        style: 'color: white'
      )
    end
  end

  def label_due_date(task)
    content_tag(:span, class: 'label label-default') do
      link_to(
        task.due_date.getlocal,
        edit_task_path(task),
        style: 'color: white'
      )
    end
  end

  def label_status(task)
    if task.status_color_name
      class_name = 'label label-' + label_lookup(task.status_color_name)
      content_tag(:span, class: class_name) do
        link_to(show_status(task), edit_task_path(task), style: 'color: white')
      end
    else
      'NA'
    end
  end

  def label_priority(task)
    if task.priority_color_name
      class_name = 'label label-' + label_lookup(task.priority_color_name)
      content_tag(:span, class: class_name) do
        link_to(show_priority(task), edit_task_path(task),
                style: 'color: white')
      end
    else
      'N/A'
    end
  end

  def label_alternate_id(task)
    if !task.alternate_id.blank?
      content_tag(:span, class: 'label label-default') do
        link_to(task.alternate_id, edit_task_path(task), style: 'color: white')
      end
    else
      ''
    end
  end

  def label_product(task)
    class_name = 'label label-' + label_lookup(task.product_color_name)
    if task.product_color_name
      content_tag(:span, class: class_name) do
        link_to(show_product(task), edit_task_path(task), style: 'color: white')
      end
    else
      'N/A'
    end
  end

  def show_time(task)
    time_spent = 0
    task.task_details.each do |detail|
      time_spent += detail.time_spent
    end
    if time_spent < 60
      content_tag(:strong,
                  pluralize(time_spent, 'minute'), class: 'label label-default')
    else
      content_tag(:strong, pluralize(
                             number_with_precision(time_spent / 60.0,
                                                   precision: 2), 'hour'),
                  class: 'label label-default')
    end
  end

  def show_color(obj)
    class_name = 'square-' + obj.color.name.downcase.gsub(' ', '').to_s
    content_tag(:div, nil, class: class_name)
  end
end

app/views/tasks/_errors.html.erb
<% if @task.errors.any? %>
  <section id="errors">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
    <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for @task, html: { class: "form-inline" } do |f| %>

  <div class="form-group form-49">
    <%= f.label :title, "Title *", class: "form-required" %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group form-49">
    <%= f.label :assigned_to, 'Assigned To *', class: "form-required" %>
    <%= f.collection_select :assigned_to, User.all.where('name is not ?', nil), :id, :name,
      { selected: current_user.id } %>
  </div>

  <div class="form-group form-49">
    <%= f.label :tag_list, 'Tag List' %>
    <%= f.text_field :tag_list, value: @task.tag_list.to_s, class: "myTags" %>
  </div>

  <div class="form-group form-49">
    <%= f.label :alternate_id, 'Alternate ID#' %>
    <%= f.text_field :alternate_id, placeholder: "Alternate ID" %>
  </div>

  <div class="form-group form-49">
    <%= f.label :client, 'Client *', class: "form-required" %>
    <% if !params[:client_id].blank? %>
      <%= f.collection_select :client_id, Client.all.order('position'), :id, :name, { selected: params[:client_id], prompt: "Choose Client...", name: "client" }, { class: "clientSelectList" } %>
    <% else %>
      <%= f.collection_select :client_id, Client.all.order('position'), :id, :name, { prompt: "Choose Client...", name: "client" }, { class: "clientSelectList" } %>
    <% end %>
    <div class="clientSelectAdd" style="display: none;">
      <a id="cancel-client" style="color:white" href="javascript:cancelClient()">Cancel</a><input placeholder="Enter new client name" type="text" name="task[client_name]" id="task_client_name">
    </div>
  </div>

  <div class="form-group form-49">
    <%= f.label :status, 'Status *', class: "form-required" %>
    <%= f.collection_select :status_id, Status.all.order('position'), :id, :name, { prompt: "Choose Status..." }, { class: "statusSelectList" } %>
    <div class="statusSelectAdd form-group" style="display: none;">
      <a id="cancel-status" style="color:white" href="javascript:cancelStatus()">Cancel</a><input placeholder="Enter new status name" type="text" name="task[status_name]" id="task_status_name">
    </div>
  </div>

  <div class="form-group form-49">
    <%= f.label :product, 'Product *', class: "form-required" %>
    <%= f.collection_select :product_id, Product.all.order('position'), :id, :name, { prompt: "Choose Product..." }, { class: "productSelectList" } %>
    <div class="productSelectAdd form-group" style="display: none;">
      <a id="cancel-product" style="color:white" href="javascript:cancelProduct()">Cancel</a><input placeholder="Enter new product name" type="text" name="task[product_name]" id="task_product_name">
    </div>
  </div>

  <div class="form-group form-49">
    <%= f.label :priority, 'Priority *', class: "form-required" %>
    <%= f.collection_select :priority_id, Priority.all.order('position'), :id, :name, { prompt: "Choose Priority..."}, { class: "prioritySelectList" } %>
    <div class="prioritySelectAdd form-group" style="display: none;">
      <a id="cancel-priority" style="color:white" href="javascript:cancelPriority()">Cancel</a><input placeholder="Enter new priority name" type="text" name="task[priority_name]" id="task_priority_name">
    </div>
  </div>

  <div class="form-group form-49">
    <%= f.label :project_id, 'Project' %>
    <%= f.collection_select :project_id, Project.all.order('title'), :id, :title, { include_blank: "" } %>
  </div>

  <div class="form-group form-49">
    <%= f.label :due_date, "Due Date" %>
    <%= f.text_field :due_date, class: "form-control" %>
  </div>

  <div class="form-group form-49">
    <%= f.label :notify_email %>
    <%= f.text_field :notify_email, placeholder: "client.name@theclientsite.com", class: "tagEmail" %>
  </div>

  <div class="form-group form-49">
    <%= f.label :billable, 'Billable?' %>
    <%= f.check_box :billable %>
  </div>

  <br/>
   <div class="form-group form-49" style="display: block;">
     <button class="btn btn-default">Submit</button>
     <%= link_to "Cancel", tasks_path, class: "btn btn-warning" %>
   </div>
<% end %>

<script>
  $("#task_client_id").append('<option value=9999>Add New Client...</option>');
  $("#task_status_id").append('<option value=9999>Add New Status...</option>');
  $("#task_priority_id").append('<option value=9999>Add New Priority...</option>');
  $("#task_product_id").append('<option value=9999>Add New Product...</option>');

  $('select[name="task[client_id]"]').change(function() {
    if ($(this).val() == "9999") {
      $(".clientSelectList").hide();
      $(".clientSelectAdd").show();
      $('#cancel-client').show();
    }
  });

  $('select[name="task[status_id]"]').change(function() {
    if ($(this).val() == "9999") {
      $(".statusSelectList").hide();
      $(".statusSelectAdd").show();
      $('#cancel-status').show();
    }
  });

  $('select[name="task[priority_id]"]').change(function() {
    if ($(this).val() == "9999") {
      $(".prioritySelectList").hide();
      $(".prioritySelectAdd").show();
      $('#cancel-priority').show();
    }
  });

  $('select[name="task[product_id]"]').change(function() {
    if ($(this).val() == "9999") {
      $(".productSelectList").hide();
      $(".productSelectAdd").show();
      $('#cancel-product').show();
    }
  });

  function cancelClient() {
    $(".clientSelectList").show();
    $(".clientSelectAdd").hide();
    $(".clientSelectList").val('1');
    $('#cancel-client').hide();
  }

  function cancelStatus() {
    $(".statusSelectList").show();
    $(".statusSelectAdd").hide();
    $(".statusSelectList").val('1');
    $('#cancel-status').hide();
  }

  function cancelPriority() {
    $(".prioritySelectList").show();
    $(".prioritySelectAdd").hide();
    $(".prioritySelectList").val('1');
    $('#cancel-priority').hide();
  }

  function cancelProduct() {
    $(".productSelectList").show();
    $(".productSelectAdd").hide();
    $(".productSelectList").val('1');
    $('#cancel-product').hide();
  }

  $('.myTags').tagit({
  });

  $('.tagEmail').tagit({
  });

  $(document).ready(function()
  {
    $('.title-question').tooltipster();
  }
);

</script>

app/views/tasks/_table.html.erb
<div class="table-responsive" id="task-list">
  <input class="search" placeholder="Quick Search" />
  <table class="table table-hover" id="sorted-table">
    <thead>
      <tr>
        <th class="table-medium"><i class="fa fa-sort"></i> ID</th>
        <th><i class="fa fa-sort"></i> Alt. ID</th>
        <th><i class="fa fa-sort"></i> Title</th>
        <th><i class="fa fa-sort"></i> Status</th>
        <th class="table-medium"><i class="fa fa-sort"></i> Client</th>
        <th><i class="fa fa-sort"></i> Product</th>
        <th><i class="fa fa-sort"></i> Priority</th>
        <th><i class="fa fa-sort"></i> Assigned To</th>
        <th class="table-large"><i class="fa fa-sort"></i> Date</th>
      </tr>
    </thead>
    <tbody class="list">
      <% @tasks.each do |task| %>
        <tr id="task_<%= task.id %>">
          <td class="sort-id"><%= label_id(task) %></td>
          <td class="sort-alternate-id"><%= label_alternate_id(task) %></td>
          <td class="sort-title"><%= truncate(task.title, length: 50, separator: ' ') %></td>
          <td class="sort-status"><%= label_status(task) %></td>
          <td class="sort-client"><%= label_client(task) %></td>
          <td class="sort-product"><%= label_product(task)  %></td>
          <td class="sort-priority"><%= label_priority(task) %></td>
          <td class="sort-assigned-to"><%= mail_to(email_for(task), assigned_to(task)) %></td>
          <td class="sort-date"><%= label_date(task) %></td>

          <td><%= link_to task, class: "btn btn-primary" do %>
              <span class="glyphicon glyphicon-book" aria-hidden="true" title="Show Details"></span>
            <% end %>
          </td>
          <% if can? :update, Task %>
            <td><%= link_to edit_task_path(task), class: "btn btn-info" do %>
                <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Edit Details"></span>
              <% end %>
            </td>
          <% end %>
          <% if can? :destroy, @task %>
            <td><%= link_to task, method: :delete, data: { confirm: "Are you sure?" },
          class: "btn btn-danger", remote: true do %>
                <span class="glyphicon glyphicon-trash" aria-hidden="true" title="Delete"></span>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/destroy.js.erb
$('#task_<%= @task.id %>').remove();

app/views/tasks/edit.html.erb
<%= render 'errors' %>
<div class="dark-matter">
  <h1>Edit Task
      <span>Modify the fields that you would like to edit. <span class="form-required">* = required field.</span></span>
  </h1>
  <%= render 'form' %>
</div>
<%= link_to "All Tasks", tasks_path %>

app/views/tasks/index.html.erb
<% if @tasks.count == 0 %>
  <h2>No tasks assigned to you with the given filter! <%= link_to "View All?", "/tasks/filters/all/alltasks" %></h2>
  <h3 style="color: black;">Read the <%= link_to "documentation", welcome_documentation_path, subdomain: false %> if you need help getting started.</h3>
  <hr/>
<% end %>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#tagcloud" aria-expanded="true" aria-controls="tagcloud">
          <strong><i class="fa fa-tags"></i> Tags</strong>
        </a>
      </h4>
    </div>
    <div id="tagcloud" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <div id="tag_cloud">
          <% tag_cloud Task.tag_counts, ['label label-primary btn-xs','label label-success label-sm','label label-danger'] do |tag, css_class| %>
            <%= link_to tag_path(tag.name), class: css_class do %>
              <%= content_tag(:span, tag.name + " ").concat(content_tag(:span, tag.count, class: "badge")) %>
            <% end %>
          <% end %>
        </div>
        <br/>
        <p>* - Tags are defined when creating or editing a task.</p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#filters" aria-expanded="false" aria-controls="filters">
          <strong><i class="fa fa-th-large"></i> Filters</strong>
        </a>
      </h4>
    </div>
    <div id="filters" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <div class="filters">
          <div class="row">
            <div class="col-md-3">
              <p><strong>Status</strong></p>
              <% @statuses.all.each do |status| %>
                <%= link_to "/tasks/filters/status/#{status.id}" do %>
                  <%= filter_label(status) %>
                <% end %>
              <% end %>
            </div>
            <div class="col-md-3">
              <p><strong>Priority</strong></p>
              <% @priorities.all.each do |priority| %>
                <%= link_to "/tasks/filters/priority/#{priority.id}" do %>
                  <%= filter_label(priority) %>
                <% end %>
              <% end %>
            </div>
            <div class="col-md-3">
              <p><strong>Product</strong></p>
              <% @products.all.each do |product| %>
                <%= link_to "/tasks/filters/product/#{product.id}" do %>
                  <%= filter_label(product) %>
                <% end %>
              <% end %>
            </div>
          </div>
          <p>* - Filters are defined in the <%= link_to "configuration", pages_index_path %> settings.</p>
        </div>
      </div>
    </div>
  </div>
</div>
    <h1 class="header"><%= link_to "Your Tasks", tasks_path %> | <small><%= link_to "Show All", "/tasks/filters/all/all_tasks" %></small> | <small><%= link_to "Due Now", due_now_tasks_path %></small></h1>
<%= link_to "New Task", new_task_path, class: "btn btn-primary" %>
<hr/>
<%= render 'tasks/table' %>
<script>
  var options = {
    valueNames: [ 'sort-id', 'sort-alternate-id', 'sort-title', 'sort-status', 'sort-status', 'sort-client', 'sort-product', 'sort-priority', 'sort-assigned-to', 'sort-date', 'sort-time' ]
  };

  var userList = new List('task-list', options);
</script>

app/views/tasks/new.html.erb
<%= render 'errors' %>
<div class="dark-matter">
  <h1>New Task
      <span>Start by entering some basic information about the task.  <span class="form-required">* = required field.</span></span>
  </h1>
  <%= render 'form' %>
</div>
<%= link_to "All Tasks", tasks_path %>

app/views/tasks/show.html.erb
<h1 class="page-header"><%= link_to @task.title, edit_task_path(@task) %></h1>
<h3 style="color: #333333;">Created by: <%= created_by(@task) %></h3>
<table class="table">
  <thead>
    <th class="table-small">ID</th>
    <th class="table-medium">Alt. ID</th>
    <th>Title</th>
    <th>Status</th>
    <th class="table-medium">Client</th>
    <th>Product</th>
    <th>Priority</th>
    <th>Assigned To</th>
    <th class="table-large">Date</th>
    <th>Time Spent</th>
  </thead>
  <tbody>
    <tr>
      <td><%= label_id(@task) %></td>
      <td><%= label_alternate_id(@task) %></td>
      <td><%= truncate(@task.title, length: 50, separator: ' ') %></td>
      <td><%= label_status(@task) %></td>
      <td><%= label_client(@task) %></td>
      <td><%= label_product(@task) %></span></td>
      <td><%= label_priority(@task) %></td>
      <td><%= mail_to(email_for(@task), assigned_to(@task)) %></td>
      <td><%= label_date(@task) %></td>
      <td><%= show_time(@task) %></td>
    </tr>
  </tbody>
</table>
<div id="tag_cloud">
  <h2>Tags</h2>
  <% tag_cloud @task.tag_counts, ['label label-warning', 'label label-warning', 'label label-warning'] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
  <hr/>
</div>
<% if attachment_count(@task) > 0 %>
  <h2>Attachments:</h2>
<% end %>
<ul>
  <% @task_details.each do |detail| %>
    <% if detail.task_attachment.file? %>
      <li><%= link_to detail.task_attachment_file_name, detail.task_attachment.url %></li>
    <% end %>
  <% end %>
</ul>
<%= link_to "New Detail", new_task_task_detail_path(@task), class: "btn btn-primary" %>
<p></p>
<p>Sort by <a onclick="sortNewest()">Newest</a> | <a onclick="sortOldest()">Oldest</a></p>
<div id="details">
<% @task_details.each do |detail| %>
  <div id="detail_<%=detail.id%>">
    <% if can? :update, detail %>
      <%= link_to [:edit, @task, detail], class: "btn btn-default btn-xs edit" do %>
        Edit
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
      <% end %>
    <% end %>
    <% if can? :destroy, detail %>
      <%= link_to [@task, detail], class: "btn btn-default btn-xs edit", method: :delete, data: { confirm: "Are you sure?" } do %>
        Delete
      <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
      <% end %>
    <% end %>
    <%= show_detail(detail) %>
    </div>
  <% end %>
</div>
<% if @task_details.count > 0 %>
  <p><%= link_to "New Detail", new_task_task_detail_path(@task), class: "btn btn-primary" %></p>
<% end %>
<%= link_to "All Tasks", tasks_path, class: "btn btn-danger" %>
<% if @task.project_id %>
<%= link_to "Return to Project", project_path(@task.project), class: "btn btn-success" %>
<% end %>

<script>
  function sortNewest() {
    tinysort('div#details>div',{attr:'id', order: 'desc'});
  }
  function sortOldest() {
    tinysort('div#details>div',{attr:'id'});
  }  
</script>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>