config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  constraints(SubdomainPresent) do
    root 'tasks#index', as: :subdomain_root
    devise_for :users
    resources :users, only: [:index, :update, :edit, :destroy]
    resources :tasks do
      collection do
        get 'search'
        get 'due_now'
      end
    end
    
    get 'tasks/filters/status/:status_id' => 'tasks#index'
    get 'tasks/filters/priority/:priority_id' => 'tasks#index'
    get 'tasks/filters/product/:product_id' => 'tasks#index'
    get 'tasks/filters/all/:all_tasks' => 'tasks#index'
    
    resources :tasks do
      resources :task_details
    end
    
    resources :clients do
      resources :client_contacts
      collection do
        post :sort
        get 'contacts'
      end
    end

    resources :statuses do
      collection { post :sort }
    end
    
    resources :priorities do
      collection { post :sort }
    end

    resources :products do
      collection { post :sort }
    end
    
    resources :projects do
      resources :tasks
    end

    resources :searches

    resources :todo_lists do
      resources :todo_items do
        member do
          patch :complete
        end
      end
    end
    
    get 'analytics/show'
    
    get 'pages/index'
    resources :billings, only: [:new, :show, :create]
    get 'tags/:tag', to: 'tasks#index', as: :tag
    get 'welcome/documentation' => 'welcome#documentation'
  end

  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
    get 'pages/test' => 'pages#test'
    get 'welcome/index' => 'welcome#index'
    get 'welcome/test' => 'welcome#test'
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items, dependent: :destroy

  validates :title, presence: true
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_errors.html.erb
<% if @todo_list.errors.any? %>
  <section id="errors">
    <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this Todo List from being saved:</h2>
    <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-actions">
    <%= f.submit "New Todo List", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>
<%= render 'errors' %>
<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>Todo Lists</h1>

<%= link_to "Add New Todo List", new_todo_list_path, class: "btn btn-primary" %>

<div class="responsive">
  <table class="table table-hover table-striped">
    <thead>
      <th>Title</th>
      <th>Description</th>
    </thead>
    <tbody>
      <% @todo_lists.each do |todo_list| %>
        <tr>
          <td><%= todo_list.title %></td>
          <td><%= todo_list.description %></td>
          <td><%= link_to todo_list, class: "btn btn-primary" do %>
              <span class="glyphicon glyphicon-book" aria-hidden="true" title="Show Details"></span>
            <% end %>
          </td>
          <% if can? :update, TodoList %>
            <td><%= link_to edit_todo_list_path(todo_list), class: "btn btn-info" do %>
                <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Edit Details"></span>
              <% end %>
            </td>
          <% end %>
          <% if can? :destroy, TodoList %>
            <td><%= link_to todo_list, method: :delete, data: { confirm: "Are you sure?" },
          class: "btn btn-danger" do %>
                <span class="glyphicon glyphicon-trash" aria-hidden="true" title="Delete"></span>
              <% end %>
            </td>
          <% end %>          
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>
<%= render 'errors' %>
<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<div class="well search">
  <div id="todo_items_wrapper">
    <%= render @todo_list.todo_items %>
  </div>
  <hr/>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
  <div class="links">
    <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
    <%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" }
   %> |
    <%= link_to 'Back', todo_lists_path %>
  </div>  
</div>