config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  constraints(SubdomainPresent) do
    root 'tasks#index', as: :subdomain_root
    devise_for :users
    resources :users, only: [:index, :update, :edit, :destroy]
    resources :tasks do
      collection do
        get 'search'
        get 'due_now'
      end
    end
    
    get 'tasks/filters/status/:status_id' => 'tasks#index'
    get 'tasks/filters/priority/:priority_id' => 'tasks#index'
    get 'tasks/filters/product/:product_id' => 'tasks#index'
    get 'tasks/filters/all/:all_tasks' => 'tasks#index'
    
    resources :tasks do
      resources :task_details
    end
    
    resources :clients do
      resources :client_contacts
      collection do
        post :sort
        get 'contacts'
      end
    end

    resources :statuses do
      collection { post :sort }
    end
    
    resources :priorities do
      collection { post :sort }
    end

    resources :products do
      collection { post :sort }
    end
    
    resources :projects do
      resources :tasks
    end

    resources :searches

    resources :todo_lists do
      resources :todo_items do
        member do
          patch :complete
        end
      end
    end
    
    get 'analytics/show'
    
    get 'pages/index'
    resources :billings, only: [:new, :show, :create]
    get 'tags/:tag', to: 'tasks#index', as: :tag
    get 'welcome/documentation' => 'welcome#documentation'
  end

  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
    get 'pages/test' => 'pages#test'
    get 'welcome/index' => 'welcome#index'
    get 'welcome/test' => 'welcome#test'
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :client
  belongs_to :user

  validates :title, :client, :allotted_time, presence: true

  def self.time_spent(project)
    time_spent = 0
    @all_tasks = project.tasks
    @all_tasks.each do |task|
      task.task_details.each do |td|
        time_spent += td.time_spent
      end
    end
    time_spent / 60.0
  end

  def allotted_time=(value)
    write_attribute(:allotted_time, value.to_i * 60.0)
  end

  def allotted_time
    read_attribute(:allotted_time).to_f / 60.0
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.includes(:client, :user, :tasks)
  end

  def show
    @project = Project.find(params[:id])
    @completed = Hash.new(0)
    @completed["Allotted Time"] = @project.allotted_time
    sum = 0
    @project.tasks.each do |pt|
      sum += pt.task_details.map(&:time_spent).inject(0, :+)
    end
    @completed["Time Spent"] = sum 
    @completed_percent = (@completed["Time Spent"] / 60.0) / @completed["Allotted Time"].to_f * 100.0
  end

  def new
    @project = Project.new
    if Task.all.count <= 1
      Task.reindex
      TaskDetail.reindex
    end
  end

  def create
    @project = Project.create(project_params)
    if @project.save
      redirect_to @project, flash: { success: "Project successfully created!" }
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, flash: { success: "Project successfully updated!" }
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:user_id, :allotted_time, :actual_time, :due_date, :title, :client_id)
    end
end

app/helpers/projects_helper.rb
# Projects Helper
module ProjectsHelper
  def time_spent(project)
    time_spent = 0
    project.tasks.each do |t|
      t.task_details.each do |td|
        time_spent += td.time_spent
      end
    end
    number_with_precision(time_spent / 60.0, precision: 2)
  end

  def time_remaining(project)
    @allotted_time_hours = allotted_time_hours(project)
    @time_spent = time_spent(project)
    @time_remaining = @allotted_time_hours.to_f - @time_spent.to_f
    number_with_precision(@time_remaining, precision: 2)
  end

  def allotted_time_hours(project)
    project.allotted_time
  end
end

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <section id="errors">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
    <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @project do |f| %>

  <% if Client.count < 1 %>
    <h2 style="color: red;">You must create a client first!  Click <%= link_to "here", new_client_path %> to add one!</h2>
  <% end %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :client_id %><br>
    <%= f.collection_select :client_id, Client.all.order('name'), :id, :name, { selected: params[:client_id], prompt: "Choose Client..." }, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Project Manager" %><br>
    <%= f.collection_select :user_id, User.all.where('name is not ?', nil), :id, :name,
      { selected: current_user.id }, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Allotted time in hours" %><br>
    <%= f.number_field :allotted_time, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :due_date %><br>
    <%= f.text_field :due_date, class: "form-control" %><br>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :client_id %><br>
    <%= f.collection_select :client_id, Client.all.order('name'), :id, :name, {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Project Manager" %><br>
    <%= f.collection_select :user_id, User.all.where('name is not ?', nil), :id, :name,
      { selected: current_user.id }, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Allotted time in hours" %><br>
    <%= f.number_field :allotted_time, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :due_date %><br>
    <%= f.text_field :due_date, class: "form-control" %><br>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/projects/index.html.erb
<h1>All Projects</h1>
<%= link_to "New Project", new_project_path, class: "btn btn-primary" %>
<div class="table-responsive">
  <table class="table table-striped table-hover" id="sorted-table">
    <thead>
      <th>Client</th>
      <th>Title</th>
      <th>Project Manager</th>
      <th>Time Allotted (hours)</th>
      <th>Time Spent</th>
      <th>Time Remaining</th>
      <th>Due Date</th>
      <th>Progress</th>
    </thead>
    <tbody>

      <% @projects.each do |project| %>
      <% completed = Hash.new %>
      <% completed["Allotted Time"] = project.allotted_time %>
      <% sum = 0 %>
      <% project.tasks.each do |pt| %>
        <% sum += pt.task_details.map(&:time_spent).inject(0, :+) %>
      <% end %>
      <% completed["Time Spent"] = sum %>
      <% completed_percent = (completed["Time Spent"] / 60.0) / completed["Allotted Time"].to_f * 100.0 %>
      <tr>
        <td><%= project.client.name %></td>
        <td><%= project.title %></td>
        <td><%= project.user.name %></td>
        <td><%= allotted_time_hours(project) %></td>
        <td><%= time_spent(project) %></td>
        <td><%= time_remaining(project) %></td>
        <td><%= project.due_date %></td>
        <td>
          <div class="progress">
            <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width:<%= number_to_percentage(completed_percent, precision: 2) %>; color: black;">
             <%= number_to_percentage(completed_percent, precision: 2) %> 
            </div>
          </div>
        </td>
        <td><%= link_to project, class: "btn btn-primary" do %>
            <span class="glyphicon glyphicon-book" aria-hidden="true" title="Show Details"></span>
          <% end %>
        </td>
        <% if can? :update, project %>
          <td><%= link_to edit_project_path(project), class: "btn btn-info" do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Edit Details"></span>
            <% end %>
          </td>
        <% end %>
        <% if can? :destroy, project %>
          <td><%= link_to project, method: :delete, data: { confirm: "Are you sure?" },
        class: "btn btn-danger" do %>
              <span class="glyphicon glyphicon-trash" aria-hidden="true" title="Delete"></span>
            <% end %>
          </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<h2><%= @project.client.name %></h2>
<div class="progress">
  <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="2"
  aria-valuemin="0" aria-valuemax="<%= @completed['Allotted Time'] %>" style="width:<%= number_to_percentage(@completed_percent, precision: 2) %>; min-width: 3%">
    <%= number_to_percentage(@completed_percent, precision: 2) %> Complete 
  </div>
</div>
<table class="table table-hover table-responsive">
  <thead>
    <th>Title</th>
    <th>Project Manager</th>
    <th>Allotted Time (hours)</th>
    <th>Time Spent</th>
    <th>Time Remaining</th>
    <th>Due Date</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @project.title %></td>
      <td><%= @project.user.name %></td>
      <td><%= allotted_time_hours(@project) %></td>
      <td><%= time_spent(@project) %></td>
      <td><%= time_remaining(@project) %></td>
      <td><%= @project.due_date %></td>
    </tr>
  </tbody>
</table>
<h2>Tasks</h2>
<div class="table-responsive">
  <table class="table table-striped table-hover" id="sorted-table">
    <thead>
      <tr>
        <th class="table-small">ID</th>
        <th class="table-medium">Alt. ID</th>
        <th>Title</th>
        <th>Status</th>
        <th class="table-medium">Client</th>
        <th>Product</th>
        <th>Priority</th>
        <th>Assigned To</th>
        <th class="table-large">Date</th>
        <th>Time Spent</th>
      </tr>
    </thead>
    <tbody>
      <% @project.tasks.each do |task| %>
        <tr>
          <td><%= label_id(task) %></td>
          <td><%= label_alternate_id(task) %></td>
          <td><%= task.title %></td>
          <td><%= label_status(task) %></td>
          <td><%= label_client(task) %></td>
          <td><%= label_product(task)  %></td>
          <td><%= label_priority(task) %></td>
          <td><%= mail_to(email_for(task), assigned_to(task)) %></td>
          <td><%= label_date(task) %></td>
          <td><%= show_time(task) %></td>
          <td><%= link_to task, class: "btn btn-primary" do %>
              <span class="glyphicon glyphicon-book" aria-hidden="true" title="Show Details"></span>
            <% end %>
          </td>
          <% if can? :update, @task %>
            <td><%= link_to edit_task_path(task), class: "btn btn-info" do %>
                <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Edit Details"></span>
              <% end %>
            </td>
          <% end %>
          <% if can? :destroy, @task %>
            <td><%= link_to task, method: :delete, data: { confirm: "Are you sure?" },
          class: "btn btn-danger" do %>
                <span class="glyphicon glyphicon-trash" aria-hidden="true" title="Delete"></span>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Add New Task", new_task_path(client_id: @project.client.id, project_id: @project.id), class: "btn btn-primary" %>
</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>