config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  constraints(SubdomainPresent) do
    root 'tasks#index', as: :subdomain_root
    devise_for :users
    resources :users, only: [:index, :update, :edit, :destroy]
    resources :tasks do
      collection do
        get 'search'
        get 'due_now'
      end
    end
    
    get 'tasks/filters/status/:status_id' => 'tasks#index'
    get 'tasks/filters/priority/:priority_id' => 'tasks#index'
    get 'tasks/filters/product/:product_id' => 'tasks#index'
    get 'tasks/filters/all/:all_tasks' => 'tasks#index'
    
    resources :tasks do
      resources :task_details
    end
    
    resources :clients do
      resources :client_contacts
      collection do
        post :sort
        get 'contacts'
      end
    end

    resources :statuses do
      collection { post :sort }
    end
    
    resources :priorities do
      collection { post :sort }
    end

    resources :products do
      collection { post :sort }
    end
    
    resources :projects do
      resources :tasks
    end

    resources :searches

    resources :todo_lists do
      resources :todo_items do
        member do
          patch :complete
        end
      end
    end
    
    get 'analytics/show'
    
    get 'pages/index'
    resources :billings, only: [:new, :show, :create]
    get 'tags/:tag', to: 'tasks#index', as: :tag
    get 'welcome/documentation' => 'welcome#documentation'
  end

  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
    get 'pages/test' => 'pages#test'
    get 'welcome/index' => 'welcome#index'
    get 'welcome/test' => 'welcome#test'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :color
  validates :name, presence: true, uniqueness: true
  validates :color, presence: true

  delegate :name, :to => :color, :prefix => true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  def index
    @products = Product.includes(:color).order("position")
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @product.save
      redirect_to @product, flash: { success: "Product successfully created!" }
    else
      render :new
    end
  end

  def update
    @product.update(product_params)
    if @product.save
      redirect_to @product, flash: { success: "Product successfully updated!" }
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, flash: { error: 'Product was successfully destroyed.' }
  end

  def sort
    super
  end  

  private

  def product_params
    params.require(:product).permit(:name, :color_id)
  end
end

app/helpers/products_helper.rb
# - Product Helper
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <section id="errors">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @product do |f| %>
  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :color_id %><br/>
    <%= f.collection_select :color_id, Color.all, :id, :name, { prompt: "Choose Color..." }, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
<%= link_to "All Clients", clients_path, class: "btn btn-info" %>
<%= link_to "Configuration", pages_index_path, class: "btn btn-info" %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Product Listing</h1>
<table class="table table-striped table-hover table-responsive" id="position_products">
  <thead>
    <th></th>
    <th>Name</th>
    <th>Color</th>
  </thead>
  <tbody data-update-url="<%= sort_products_url %>">
  <% @products.each do |product| %>
    <%= content_tag_for :tr, product do %>
      <td><i class="fa fa-arrows-alt"></i></td>
      <td><%= product.name %></td>
      <td><%= show_color(product) %></td>
      <td><%= link_to product, class: "btn btn-primary" do %>
        <span class="glyphicon glyphicon-book" aria-hidden="true" title="Show Details"></span>
        <% end %>
      </td>
      <% if can? :update, product %>
      <td><%= link_to edit_product_path(product), class: "btn btn-info" do %>
        <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Edit Details"></span>
        <% end %>
      </td>
      <% end %>
      <% if can? :destroy, product %>
      <td><%= link_to product, method: :delete, data: { confirm: "WARNING!: DELETING A PRODUCT WILL REMOVE ALL TASKS ASSOCIATED WITH THIS PRODUCT!  CONSIDER UPDATING EXISTING TASKS TO A NEW PRODUCT FIRST!" },
        class: "btn btn-danger" do %>
          <span class="glyphicon glyphicon-trash" aria-hidden="true" title="Delete"></span>
        <% end %>
      </td>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>
<% if Product.all.count > 1 %>
  <p>Drag and drop on <i class="fa fa-arrows-alt"></i> to change sort order.</p>
<% end %>
<%= link_to "New Product", new_product_path, class: "btn btn-success" %>
<%= link_to "Configuration", pages_index_path, class: "btn btn-info" %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1>Product Details <small><%= link_to "edit", edit_product_path(@product) %></small></h1>
<table class="table table-striped table-responsive table-hover">
  <thead>
    <th>Name</th>
    <th>Color</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @product.name %></td>
      <td><%= show_color(@product) %></td>
    </tr>
  </tbody>
</table>
<p>
  <%= link_to "New Product", new_product_path, class: "btn btn-success" %>
</p>
<%= link_to "All Products", products_path, class: "btn btn-info" %>
<%= link_to "Configuration", pages_index_path, class: "btn btn-info" %>